dataset: "ESD"

path:
  corpus_path: "{PATH}/ESD"
  lexicon_path: "./preprocess/lexicon/new_librispeech-lexicon.txt"
  raw_path: "{PATH}/ESD/raw_data"
  preprocessed_path: "{PATH}/ESD/preprocessed_data"

preprocessing:
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 